version: "3.5"
services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio:/verdaccio/conf
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./elasticsearch/data:/usr/share/elasticsearch/data
  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:8.11.3
  #   volumes:
  #     - ./logstash/config:/logstash/config
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - elasticsearch
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.11.3
  #   environment:
  #     - ELASTICSEARCH_URL=http://0.0.0.0:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - name=postgres_con
      # - POSTGRES_DB=login 
      - POSTGRES_USER=neerajd
      - POSTGRES_PASSWORD=neerajd12345
    volumes:
      - /home/neeraj/postgres/data/:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  # artifactory:
  #   image: docker.bintray.io/jfrog/artifactory-oss:latest
  #   container_name: artifactory
  #   # networks:
  #     # - artifactory-network
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g -Xss256k -XX:+UseG1GC
  #   volumes:
  #     - /path/to/system.yaml:/var/opt/artifactory/var/etc/system.yaml
  # router:
  #   image: docker.bintray.io/jfrog/artifactory-router:latest
  #   container_name: artifactory-router
  #   ports:
  #     - "8046:8046"
  #   environment:
  #     - ARTIFACTORY_URL=http://localhost:8081/artifactory
  #   depends_on:
  #     - artifactory
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - verdaccio
    ports:
      - "83:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"