version: "3.5"
services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio:/verdaccio/conf

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - verdaccio
    ports:
      - "81:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"