storage: ./storage
publish:
  allow_offline: true
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  myPrivate:
    url: http://localhost:4873
    max_users: 100
packages:
  "@*/*":
    access: $all
    publish: $all
    proxy: npmjs
  "@private/*":
    access: $all
    publish: $all
    proxy: myPrivate
  "**":
    access: $all
    publish: $all
    proxy: npmjs
log:
  - { type: stdout, format: pretty, level: http }